### ISSUE TITLE
Cannot tap to move cursor in input fields

### ISSUE THREAD

**Issue by raihle** [LWJerri/Pauperial#12]
When writing on mobile I can usually tap in an input field to move the cursor, or tap and hold to select text. This seems to be disabled as no matter where in an input field I tap the cursor keeps its previous position.

Firefox 95.2.0 on Android OnePlus 6.

**Comment by LWJerri** [comment]
Hello! I think to commit https://github.com/LWJerri/Pauperial/commit/329265e17b5bd20340f89ffa382c6c8ea40930e2 must resolve your problem. Let me know it.

**Comment by raihle** [comment]
Yup, better now.
